apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:dev, applications, get, */*, allow
    p, role:viewer, applications, get, argocd/*, allow
    g, admin@example.com, role:admin
    g, dev@example.com, role:dev
    g, viewer@example.com, role:viewer
